**Step-1: Import packages**

In [1]:
import pandas as pd # data frame
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

**Step-2: Create a data frame using list**

In [3]:
names=['Ram','Shyam','Ghanshyam']
pd.DataFrame(names)

           0
0        Ram
1      Shyam
2  Ghanshyam

**Step-3: I want to change the index**

In [5]:
names=['Ram','Shyam','Ghanshyam']
idx=[1,2,3]
pd.DataFrame(names,idx)

           0
1        Ram
2      Shyam
3  Ghanshyam

**Step-4: Add the columns**

In [6]:
names=['Ram','Shyam','Ghanshyam']
idx=[1,2,3]
cols=['Names']
pd.DataFrame(names,idx,cols)

       Names
1        Ram
2      Shyam
3  Ghanshyam

**Step-5: Data and columns**

In [7]:
names=['Ram','Shyam','Ghanshyam']
idx=[1,2,3]
cols=['Names']
pd.DataFrame(names,columns=cols)

       Names
0        Ram
1      Shyam
2  Ghanshyam

In [8]:
names=['Ram','Shyam','Ghanshyam']
idx=[1,2,3]
cols=['Names']
pd.DataFrame(names,idx,columns=cols)

       Names
1        Ram
2      Shyam
3  Ghanshyam

**Step-6: Multiple columns**

In [12]:
names=['Ram','Shyam','Ghanshyam']
age=[20,22,24]
cols=['Names','Age']
df=pd.DataFrame(zip(names,age),columns=cols)
df

       Names  Age
0        Ram   20
1      Shyam   22
2  Ghanshyam   24

In [15]:
names=['Ram','Shyam','Ghanshyam']
age=[20,22,24]
cols=['age','name']
pd.DataFrame(zip(age,names),columns=cols)

   age       name
0   20        Ram
1   22      Shyam
2   24  Ghanshyam

**Step-7: Add a new column to already exsisted**

- in above first we have taken data

- then created a dataframe

- now we want to add new data based on requirement

In [16]:
city=['Hyd','Pune','Blr']
df['City']=City
df

       Names  Age  City
0        Ram   20   Hyd
1      Shyam   22  Pune
2  Ghanshyam   24   Blr

In [17]:
df['Marks']=[20,30]

ValueError: Length of values (2) does not match length of index (3)

In [18]:
df['Marks']=[20,33,40,50]

ValueError: Length of values (4) does not match length of index (3)

In [19]:
df['Marks']=[80,90,100]
df

       Names  Age  City  Marks
0        Ram   20   Hyd     80
1      Shyam   22  Pune     90
2  Ghanshyam   24   Blr    100

**Step-8: Update the column with new values**

In [21]:
df['Marks']=[75,85,95]
df

       Names  Age  City  Marks
0        Ram   20   Hyd     75
1      Shyam   22  Pune     85
2  Ghanshyam   24   Blr     95

**Step-9: Create empty data frame and add the columns**

In [22]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [3]:
df=pd.DataFrame()
df['Names']=['Ram','Shyam','Ghanshyam']
df['Age']=[20,22,24]
df['City']=['Hyd','Pune','Blr']
df

       Names  Age  City
0        Ram   20   Hyd
1      Shyam   22  Pune
2  Ghanshyam   24   Blr

In [4]:
df['Marks']=[80,90,100]
df

       Names  Age  City  Marks
0        Ram   20   Hyd     80
1      Shyam   22  Pune     90
2  Ghanshyam   24   Blr    100

**Step-10: Create a dataframe using dictionary**

In [27]:
d={'Names':['Ram','Shyam','Ghanshyam'],
   'Age':[20,30,40],
   'City':['hyd','Pune','Blr']}
df=pd.DataFrame(d)
df

       Names  Age  City
0        Ram   20   hyd
1      Shyam   30  Pune
2  Ghanshyam   40   Blr

In [31]:
d={'Name':'Ramesh',
   'Age':20,
   'City':'Hyd'}
pd.DataFrame(d)

ValueError: If using all scalar values, you must pass an index

In [32]:
d={'Name':'Ramesh',
   'Age':20,
   'City':'Hyd'}
pd.DataFrame(d,index=[1])

     Name  Age City
1  Ramesh   20  Hyd

**Step-11: Save the dataframe**

In [33]:
# file handling session
# directory//filename.ext
# filename.ext
# we are saving dataframes
# .csv or .xlsx

df.to_csv('data.csv')

In [34]:
df.to_excel('data.xlsx')

**Step-12: Read the dataframe**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [73]:
d={'Names':['Ram','Shyam','Ghanshyam'],
   'Age':[20,30,40],
   'City':['hyd','Pune','Blr']}
df=pd.DataFrame(d)
df

       Names  Age  City
0        Ram   20   hyd
1      Shyam   30  Pune
2  Ghanshyam   40   Blr

In [74]:
df.to_excel('data.xlsx',index=False) # then new column not created when idx=False

In [75]:
pd.read_excel('data.xlsx')

       Names  Age  City
0        Ram   20   hyd
1      Shyam   30  Pune
2  Ghanshyam   40   Blr

In [67]:
df.to_csv('data.csv',index=False)

In [68]:
pd.read_csv('data.csv')

       Names  Age  City
0        Ram   20   hyd
1      Shyam   30  Pune
2  Ghanshyam   40   Blr

In [76]:
df['Marks']=[80,90,95]
df

       Names  Age  City  Marks
0        Ram   20   hyd     80
1      Shyam   30  Pune     90
2  Ghanshyam   40   Blr     95

**Step-13: Drop the column**

- labels
  
- axis

- index

- columns

- level

- inplace

In [30]:
# if i want ot drop a index
# i need to use index argument name
df.drop(index=0)

       Names  Age  City  Marks
1      Shyam   30  Pune     90
2  Ghanshyam   40   Blr     95

In [37]:
df

       Names  Age  City  Marks
0        Ram   20   hyd     80
1      Shyam   30  Pune     90
2  Ghanshyam   40   Blr     95

In [32]:
# if i want ot drop a column
# i need to use index argument name
df.drop(columns='Marks')

       Names  Age  City
0        Ram   20   hyd
1      Shyam   30  Pune
2  Ghanshyam   40   Blr

In [33]:
df.drop(columns=['City','Marks'])

       Names  Age
0        Ram   20
1      Shyam   30
2  Ghanshyam   40

In [ ]:
df.drop('marks')# if i don't give argument lable
df.drop(1) # 1 become label
#######################################################
# we need to axis
# axis = 0 indicates index

In [39]:
df.drop('Marks',axis=1)

       Names  Age  City
0        Ram   20   hyd
1      Shyam   30  Pune
2  Ghanshyam   40   Blr

In [42]:
df.drop(1)

       Names  Age City  Marks
0        Ram   20  hyd     80
2  Ghanshyam   40  Blr     95

In [44]:
df.drop('Age',axis=1)

       Names  City  Marks
0        Ram   hyd     80
1      Shyam  Pune     90
2  Ghanshyam   Blr     95

In [46]:
df.drop('Names',axis=1)

   Age  City  Marks
0   20   hyd     80
1   30  Pune     90
2   40   Blr     95

In [47]:
df.drop(['Names','Age'],axis=1)

   City  Marks
0   hyd     80
1  Pune     90
2   Blr     95

In [48]:
df.drop(['City','Marks'],axis=1)

       Names  Age
0        Ram   20
1      Shyam   30
2  Ghanshyam   40

**inplace**

- when we do the operation the result output is not over writing

- means the original dataframe is same as it is.

- in order to do this we need to use **inpalce**

- by default inplace = False

- make **inplace=True** if you want overwrite the result

In [49]:
df

       Names  Age  City  Marks
0        Ram   20   hyd     80
1      Shyam   30  Pune     90
2  Ghanshyam   40   Blr     95

In [77]:
df.drop('Marks',axis=1,inplace=True)

In [70]:
df

       Names  Age  City
0        Ram   20   hyd
1      Shyam   30  Pune
2  Ghanshyam   40   Blr

In [71]:
df.drop('City',axis=1,inplace=True)

In [72]:
df

       Names  Age
0        Ram   20
1      Shyam   30
2  Ghanshyam   40

**Step-14: Rename the column**

In [78]:
d={'City':'city'} # {old:new}
df.rename(mapper=d,axis=1,inplace=True)

In [79]:
df

       Names  Age  city
0        Ram   20   hyd
1      Shyam   30  Pune
2  Ghanshyam   40   Blr

In [85]:
d={'city':'City'} # {old:new}
df.rename(d,axis=1,inplace=True)

In [86]:
df

       Names  Age  City
0        Ram   20   hyd
1      Shyam   30  Pune
2  Ghanshyam   40   Blr

In [80]:
d={'City':'city'}
idx={'Names':'names',
    'Age':'age',
    'city':'city'} # {old:new}
df.rename(index=idx,axis=1,inplace=True)

TypeError: Cannot specify both 'axis' and any of 'index' or 'columns'

In [87]:
d={
    'x': [1,2,3,4,5,6,7,8,9,10],
    'y': [1,4,9,16,25,36,49,64,81,100],
    'z': [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]
}
df=pd.DataFrame(d)

In [88]:
df

    x    y     z
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
4   5   25   125
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

In [91]:
x=list(range(1,11))
y=[i*i for i in x]
z=[i**3 for i in x]
df=pd.DataFrame(zip(x,y,z),columns=['X','Y','Z'])
df

    X    Y     Z
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
4   5   25   125
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

- len

- shape : df.shape

- size : df.size

- head : df.head

- tail : df.tail

- isnull : df.isnull

- dtypes : df.dtypes

- info : df.info

In [94]:
len(df)

10

In [95]:
df.shape

(10, 3)

In [96]:
df.size

30

In [99]:
df.head()

   X   Y    Z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125

In [100]:
df.tail()

    X    Y     Z
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

In [102]:
df.isnull()

       X      Y      Z
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
6  False  False  False
7  False  False  False
8  False  False  False
9  False  False  False

In [109]:
df.isnull().sum()  # true count

X    0
Y    0
Z    0
dtype: int64

In [105]:
df.dtypes
# if any cat columns occures
# it represents as object
# int === int64

X    int64
Y    int64
Z    int64
dtype: object

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       10 non-null     int64
 1   Y       10 non-null     int64
 2   Z       10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes

**Step-15: Select a columns**

In [110]:
df.columns

Index(['X', 'Y', 'Z'], dtype='object')

In [124]:
df['Z'] # no column name here (selecting one particular column)

0       1
1       8
2      27
3      64
4     125
5     216
6     343
7     512
8     729
9    1000
Name: Z, dtype: int64

In [125]:
df['Z'].values

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [128]:
df['Z'].values.tolist()

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [112]:
df[['X','Y']] # col name indicates data frame (two list means data frame)

    X    Y
0   1    1
1   2    4
2   3    9
3   4   16
4   5   25
5   6   36
6   7   49
7   8   64
8   9   81
9  10  100

In [127]:
df[['Y','Z']].values

array([[   1,    1],
       [   4,    8],
       [   9,   27],
       [  16,   64],
       [  25,  125],
       [  36,  216],
       [  49,  343],
       [  64,  512],
       [  81,  729],
       [ 100, 1000]])

In [129]:
df[['Y','Z']].values.tolist()

[[1, 1],
 [4, 8],
 [9, 27],
 [16, 64],
 [25, 125],
 [36, 216],
 [49, 343],
 [64, 512],
 [81, 729],
 [100, 1000]]

In [117]:
type(df['X'])
# 1d 
# series means one square bracket one dimension

pandas.core.series.Series

In [118]:
type(df[['X','Y']])
# 2d
# dataframe means 2 dimension

pandas.core.frame.DataFrame

In [119]:
df['X'].shape

(10,)

In [120]:
df[['X','Y']].shape

(10, 2)